### ISSUE TITLE
Playing HTML template with parameter

### ISSUE THREAD

**Issue by Sega01** [SuperFlyTV/casparcg-connection#158]
I want to play a HTML file with some parameters. 
Im already able to play it with the "play" or "playHtmlPage" function. But none of these have parameter/variables.

Which function do I have to use (if there is one, but I can't imagine there's none) to pass my variables?

**Comment by krinteron** [comment]
A lot of time has passed, but maybe someone will come in handy.
This code is for version 6.0.0

`import { CasparCG } from 'casparcg-connection';

const connectionParams = {
  host: 'localhost',
  port: 5250,
  autoConnect: true,
};

const connection = await new CasparCG(connectionParams);

const textEncoder = (text) => {
  if (typeof text !== 'string') return '';
  const result = text
    .trim()
    .concat('#####')
    .split('#')
    .reduce((acc, value, id) => {
      acc['f' + id] = value;
      return acc;
    }, {});
  return JSON.stringify(JSON.stringify(result));
};

const textForHTML = textEncoder(['text1', 'text2', 'text3']);

const startParams = {
  channel: 1,
  layer: 20,
  cgLayer: 1,
  playOnLoadLayer: 1,
  template: 'awesomeHTML',
  data: textForHTML,
};

// start
connection.cgAdd(startParams);

// stop
const stopParams = {
  channel: 1,
  layer: 20,
  cgLayer: 1,
};

connection
  .cgStop(stopParams)
  .then(
    () =>
      new Promise((resolve) => {
        // timeout of 2 seconds to complete the animation in the HTML template
        setTimeout(resolve, 2000);
      })
  )
  .then(() => this.connection.cgRemove(stopParams)); // remove the layer so that the info command returns a valid state
`

**Comment by nytamin** [comment]
Thanks @krinteron for explaining!
