### ISSUE TITLE
Accessing HTML template return values

### ISSUE THREAD

**Issue by crambow** [SuperFlyTV/casparcg-connection#164]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ X ] question about how to use this project

* **Summary**
Is it possible to access a javascript return value or the console log with casparcg-connection?
For example: I have a timer running in my HTML template and at some points I would like to invoke a function from my server application to get the current timestamp from the template.
If it is not possible like I described it, are there any suggestions how to achieve that?

**Comment by baltedewit** [comment]
This isn't exposed over the AMCP protocol so we cannot implement it in the connection library.

It may be possible to attach a file listener to the casparcg server log file or otherwise my suggestion would be to implement an HTTP or websocket server in your control application that the template may connect to.
