### ISSUE TITLE
Length parameter default value

### ISSUE THREAD

**Issue by nytamin** [SuperFlyTV/casparcg-connection#7]
If I provide the argument length=0 (like in a PlayCommand) the command sent to Caspar will be " [..] LENGTH 0", I'd like to suggest that the default value of length parameter is 0, and that will not generate a LENGTH command at all. (or is there a situation where you might want to send a "LENGTH 0" - command?)

**Comment by baltedewit** [comment]
The default value for LENGTH is not 0 according to the AMCP 2.1 guide but it is to be ommitted entirely.

If you provide the argument, why wouldn't it be sent to CasparCG?

**Comment by nytamin** [comment]
Yes yes, I know. However on the input side of ccg-connection, if the default value is "undefined" and I have an int containing the seek value to begin with, it is nice to have a default value, or "null" perhaps, because this allows for cleaner code. As it is now the code will look like:
(please excuse formatting and pseudo code, I'm on mobile) 

new PlayCommand(
{
clip: "amb", 
seek: mySeekVar||undefined, //int, or null 
length: myLengthVar||undefined, //int or null 
} 

By treating any falsy value as "undefined" /"omitted", the code upstream will look more clean:

new PlayCommand(
{
clip: "amb", 
seek: mySeekVar, 
length: myLengthVar, 
}

**Comment by jesperstarkar** [comment]
This issue has two questions:

1. Should a length parameter of 0 be threathed truthy or falsy in validation. In other words, is `LENGTH 0` a valid AMCP parameter? 

-  The AMCP Wiki doesn't mention 0.
- The AMCP command describer doesn't mention 0.
- The FFMPEG producer implementation doesn't handle this situastion, in fact `LENGTH -1` gives `202 LOADBG OK`

**I think we should allow `LENGHT 0`.** I don't se any use case for it, but we have no reason to invalidate 0. However (arguing against myself here:), I will propose that we stick with saying that frame-based values should be positive integers, as ccg-connection does today. The reason for this is to have the idea of the validator actually looking up the specific clip length when dealing with frame-based validation in the future, hence being smarter than just saying _"a number: oh, you're valid"_. However, once we se AMCP implementations giving relative seeking (a CasparCG pull-request at the moment), we should omit this and make negative values valid. 

2. What you really ask for is a safe default value that is falsy. Instead of `0` you can currently use `-1`, or perhaps even `Number.NEGATIVE_INFINITY` for future compability. `undefined` works well at the moment, and I spottet a bug with `null`. 

**I will add support for having null as a falsy value.**

Does this solve your issue?

**Comment by nytamin** [comment]
Yep, I agree with your reasoning! Using null is a cleaner way than undefined I think.

**Comment by jesperstarkar** [comment]
#8
