### ISSUE TITLE
Remove terminating characters from cgUpdate data parameter

### ISSUE THREAD

**Issue by Fixy250185** [SuperFlyTV/casparcg-connection#98]
Found an issue when serial input is sent to Caspar template using cgUpdate relating to the terminating characters (\r\n). When these characters are present in the data, it will result in malformed JSON and Caspar will not accept the string.

I believe that the TemplateDataValidator class could be modified to remove these characters from the properties of the data object by using a regex (e.g. /\r?\n|\r/g).

I can make the appropriate changes and test the solution to ensure it is working.

**Comment by baltedewit** [comment]
If you pass the data as an object, the `JSON.stringify` function should already escape the `\r\n` sequence.

If you add a branch for string types in https://github.com/SuperFlyTV/casparcg-connection/blob/master/src/lib/ParamValidators.ts#L512 then I don't see any issues with merging that. I'd prefer if you'd escape the `\r\n` sequence though, rather than remove it.

**Comment by Fixy250185** [comment]
Ok, this is what I've come up with

```javascript
// data is string: escape \r\n characters
else if (typeof data === 'string' && data !== null) {
  stringCast = stringCast.replace(/\r|\n/g, charToEscape => {
  return charToEscape === "\r" ? "\\r" : "\\n"
});
```
if a string is sent as template data, it will find matches for the \n or \r characters and replace them with an escaped version. Would this be acceptable?
